service: nodary-stamp-pool

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: eu-west-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            # - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource:
            - { "Fn::GetAtt": ["SignedDataPool", "Arn"] }

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
# package:
#  patterns:
#    - '!exclude-me.js'
#    - '!exclude-me-dir/**'
#    - include-me.js
#    - include-me-dir/**

functions:
  upsertData:
    handler: src/handlers.upsertData
    events:
      - httpApi:
          path: /
          method: post
  getData:
    handler: src/handlers.getData
    events:
      - httpApi:
          path: /{beaconId}
          method: get
  listData:
    handler: src/handlers.listData
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    SignedDataPool:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: signedDataPool
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: beaconId
            AttributeType: S
          # - AttributeName: airnode
          #   AttributeType: S
          # - AttributeName: templateId
          #   AttributeType: S
        KeySchema:
          - AttributeName: beaconId
            KeyType: HASH
          # - AttributeName: airnode
          #   KeyType: HASH
          # - AttributeName: templateId
          #   KeyType: RANGE
