service: nodary-signature-pool
useDotenv: true
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x

  stage: dev
  region: us-east-2

  httpApi:
    disableDefaultEndpoint: true
    id: ${env:HTTP_API_ID}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
            - "dynamodb:Query"

          Resource:
            - { "Fn::GetAtt": ["SignedDataPool", "Arn"] }

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
# package:
#   patterns:
#     - "!.build/**"
#     - "!.vscode/**"
#     - "!node_modules/**"
#     - "!test/**"

functions:
  upsertData:
    handler: src/handlers.upsertData
    events:
      - httpApi:
          path: /
          method: post
  getData:
    handler: src/handlers.getData
    events:
      - httpApi:
          path: /{airnode}
          method: get
  listData:
    handler: src/handlers.listData
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    SignedDataPool:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: signedDataPool
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: airnode
            AttributeType: S
          - AttributeName: templateId
            AttributeType: S
        KeySchema:
          - AttributeName: airnode
            KeyType: HASH
          - AttributeName: templateId
            KeyType: RANGE
